# This file was generated by the {rix} R package v0.11.0 on 2024-11-11
# with following call:
# >rix(r_ver = "019f5c29c5afeb215587e17bf1ec31dc1913595b",
#  > r_pkgs = c("shiny",
#  > "httr",
#  > "jsonlite",
#  > "lubridate",
#  > "data.table",
#  > "tidyverse",
#  > "leaflet",
#  > "ckanr",
#  > "sciplot",
#  > "plotrix",
#  > "purrr"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = NULL,
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses nixpkgs' revision 019f5c29c5afeb215587e17bf1ec31dc1913595b for reproducibility purposes
# which will install R version 4.3.3.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/019f5c29c5afeb215587e17bf1ec31dc1913595b.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      ckanr
      data_table
      httr
      jsonlite
      leaflet
      lubridate
      plotrix
      purrr
      sciplot
      shiny
      tidyverse;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}